### ISSUE TITLE
I can't run it on my server 

### ISSUE THREAD

**Issue by SalimF** [Trigus42/crunchyroll-dl#2]
After installing all required modules I got this error :- 

```
no display found. Using non-interactive Agg backend
Traceback (most recent call last):
  File "/usr/local/sbin/crunchyroll_downloader.py", line 308, in <module>
    config["general"]["ffmpeg_location"] = filedialog.askopenfilename(title = "ffmpeg")
  File "/usr/lib/python3.6/tkinter/filedialog.py", line 375, in askopenfilename
    return Open(**options).show()
  File "/usr/lib/python3.6/tkinter/commondialog.py", line 39, in show
    w = Frame(self.master)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2744, in __init__
    Widget.__init__(self, master, 'frame', cnf, {}, extra)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2292, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2259, in _setup
    _default_root = Tk()
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by Trigus42** [comment]
This is because Tkinter can't acess your window manager to open a GUI (I assume because you are running your server headless).
You can use the option -nf to type in the path of ffmpeg manually.
However I acually didn't test it on Linux and just now I don't know how youtube-dl handles the ffmpeg executable on Linux. I guess if you installed ffmpeg via apt or pacman it should be fine to leave the path clear when it promts you to type it in. Otherwise use 'which ffmpeg' to print the path to your ffmpeg executale.

**Comment by Trigus42** [comment]
With the [latest commit](https://github.com/Trigus42/crunchyroll-dl/commit/ffca21d676e13e3ed098b16b2cb7eedecc8acb3e) this issue should now be fixed.
