### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Figgyee** [Trigus42/crunchyroll-dl#3]
Extreme noob here. I installed the required modules and the program seems to start fine, but when I try to download something it gives me this error: 

Traceback (most recent call last):
  File "C:\Users\MYUSERNAME\Desktop\crunchyroll-dl-master\crunchyroll_downloader.py", line 318, in <module>
    PATH_ffmpeg = os.path.normpath(which("ffmpeg"))
  File "C:\Users\MYUSERNAME\AppData\Local\Programs\Python\Python39\lib\ntpath.py", line 452, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Trigus42** [comment]
That was indeed a bug. Fixed it in https://github.com/Trigus42/crunchyroll-dl/commit/7910ec3c89de4472f5e9507b2b1e325545047c92

**Comment by Figgyee** [comment]
Thank you very much Trigus42, have a nice day!

Il giorno mer 14 apr 2021 alle ore 13:18 Trigus42 ***@***.***>
ha scritto:
