### ISSUE TITLE
The program crashes on anime selection

### ISSUE THREAD

**Issue by KapDecy** [Trigus42/crunchyroll-dl#4]
Hi, I'm trying to download "those snow white notes", but can't do that.
The program keeps giving me the same error:

D:\Users\Denis.HOME-PC>"C:/Program Files/Python38/python.exe" d:/documents/projects/crunchyroll-dl/crunchyroll_downloader.py
Choose an anime or enter a URL:
> https://www.crunchyroll.com/ru/those-snow-white-notes
Traceback (most recent call last):
  File "d:/documents/projects/crunchyroll-dl/crunchyroll_downloader.py", line 380, in <module>
    w_anime.get_info()
  File "d:/documents/projects/crunchyroll-dl/crunchyroll_downloader.py", line 141, in get_info
    playlist_info = self.playlist_ie._real_extract(self.config["url"])
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\extractor\crunchyroll.py", line 665, in _real_extract
    show_id = self._match_id(url)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\extractor\common.py", line 422, in _match_id
    assert m
AssertionError

**Comment by Trigus42** [comment]
The extractor doesn't like the country tag in the URL. It uses regex matching to check if the URL is valid and the regex doesn't allow for `/ru/`, `/de/` and so on.
Just remove it and it should work. However, I'll fix this soon.
